// Core domain types for AIVA

export type BusinessType = "clinic" | "salon" | "restaurant" | "hotel";

export interface Business {
  id: string;
  name: string;
  type: BusinessType;
  phone: string;
  // Direct line for human transfers; falls back to `phone` when unset.
  staffPhone?: string;
  address: string;
  hours: string;
  languages: string[];
  services: Service[];
  faqs: Faq[];
  menu?: MenuItem[]; // restaurants only
  rooms?: RoomType[]; // hotels only
}

export interface Service {
  id: string;
  name: string;
  durationMinutes: number;
  price: number;
}

export interface Faq {
  id: string;
  question: string;
  answer: string;
}

export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  available: boolean;
}

export interface RoomType {
  id: string;
  name: string;
  pricePerNight: number;
  capacity: number;
  available: number;
}

export interface Appointment {
  id: string;
  businessId: string;
  customerName: string;
  customerPhone: string;
  serviceId: string;
  serviceName: string;
  date: string; // YYYY-MM-DD
  time: string; // HH:mm
  status: "confirmed" | "cancelled" | "completed";
  notes?: string;
  createdAt: string;
  // Set once the reminder engine has texted this appointment (dedup guard).
  reminderSentAt?: string;
}

export interface OrderItem {
  name: string;
  quantity: number;
  price: number;
  notes?: string;
}

export interface Order {
  id: string;
  businessId: string;
  customerName: string;
  customerPhone: string;
  items: OrderItem[];
  total: number;
  type: "pickup" | "delivery";
  address?: string;
  status: "pending" | "confirmed" | "ready" | "completed" | "cancelled";
  createdAt: string;
  // Set when the kitchen confirms — lets AIVA quote pickup times.
  estimatedReadyAt?: string;
}

export interface CallTranscriptTurn {
  role: "caller" | "aiva";
  text: string;
  timestamp: string;
}

export interface CallLog {
  id: string;
  businessId: string;
  callerPhone: string;
  language: string;
  channel?: "phone" | "web";
  startedAt: string;
  endedAt?: string;
  outcome:
    | "appointment_booked"
    | "order_taken"
    | "faq_answered"
    | "transferred"
    | "missed"
    | "in_progress";
  transcript: CallTranscriptTurn[];
  // Post-call intelligence (generated by Claude after the call ends)
  summary?: string;
  sentiment?: "positive" | "neutral" | "negative";
  intent?: "booking" | "order" | "question" | "complaint" | "reschedule" | "other";
  resolved?: boolean; // did AIVA fully resolve the caller's need?
  actionItems?: string[];
  upsellOpportunity?: string;
}

// A caller waiting for a slot to open up on a full day. When a cancellation
// frees a slot, the first matching entry is notified by SMS automatically.
export interface WaitlistEntry {
  id: string;
  businessId: string;
  customerName: string;
  customerPhone: string;
  serviceName: string;
  date: string; // YYYY-MM-DD they want
  status: "waiting" | "notified" | "booked" | "expired";
  createdAt: string;
  notifiedAt?: string;
}

// A follow-up task for staff, created by AIVA (callback requests,
// unresolved questions, post-call action items).
export interface ActionItem {
  id: string;
  businessId: string;
  callId?: string;
  text: string;
  customerPhone?: string;
  done: boolean;
  createdAt: string;
}
